platform: x64

environment:
  fast_finish: true
  matrix:
    - VSVER: 12
    - VSVER: 14

configuration:
    - shared

before_build:
    - ps: >-
        If ($env:Platform -Match "x86") {
            $env:VCVARS_PLATFORM="x86"
            $env:TARGET="VC-WIN32 no-asm"
        } Else {
            $env:VCVARS_PLATFORM="amd64"
            $env:TARGET="VC-WIN64A-masm"
        }
    - ps: >-
        If ($env:Configuration -Match "shared") {
            $env:SHARED="no-makedepend"
        } Else {
            $env:SHARED="no-shared no-makedepend"
        }
    - ps: $env:VSCOMNTOOLS=(Get-Content ("env:VS" + "$env:VSVER" + "0COMNTOOLS"))
    - call "%VSCOMNTOOLS%\..\..\VC\vcvarsall.bat" %VCVARS_PLATFORM%
    - mkdir _build
    - cd _build
    - perl ..\Configure %TARGET% %SHARED%
    - perl configdata.pm --dump
    - cd ..

build_script:
    - cd _build
    - nmake build_all_generated 2>&1
    - nmake PERL=no-perl 2>&1
    - cd ..

test_script:
    - cd _build
    - nmake test V=1 2>&1
    - mkdir ..\install%VSVER%
    - nmake install DESTDIR=..\install%VSVER% 2>&1
    - cd ..

artifacts:
  - path: install%VSVER%